# Send serial data from a csv file generated by Logic

import csv
import serial
import time

# Define the serial port parameters
SERIAL_PORT = '/dev/tty.usbserial-0001'  # Replace with your serial port name
BAUD_RATE =  115200  # Adjust according to your device's requirements
CSV_FILE = 'rangefinder.csv'
last_send = 0

# Open the serial port
ser = serial.Serial(SERIAL_PORT, BAUD_RATE, timeout=1)

# Read and process the CSV file
try:
    with open(CSV_FILE, 'r') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            # Get the time and value from the CSV row
            start_time = float(row['Time [s]'])
            hex_string = row['Value']
            hex_value = int(hex_string, 16)
            
            # Schedule the write operation at the specified start time
            time.sleep(start_time - last_send)
            last_send = start_time
            ser.write(hex_value.to_bytes(1, 'little'))
        print("Operation completed, press ctrl+C to quit")
except KeyboardInterrupt:
    ser.close()
# Keep the main thread alive so scheduled operations can complete